@echo off

echo Starting Go backend...
start "Go Backend" cmd /k "go run main.go"

echo Starting React frontend...
start  "React Frontend" cmd /k "cd frontend && npm start"

echo Both services are running...
